name: Build Kernel

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download and Setup Proton Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang toolchain
          
      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchain/bin/aarch64-linux-android-
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          
          make O=out m31_defconfig
          make O=out -j$(nproc)
